### ISSUE TITLE
How can I make sure caching is working ?

### ISSUE THREAD

**Issue by Dofarian** [vitaliy-bobrov/ionic-img-cache#13]
I found the caching folder on my phone but it's empty, it only contains a 0kb file. How can i make sure caching is working ?

**Comment by vitaliy-bobrov** [comment]
You can enable logging to browser console to see what was chached https://github.com/vitaliy-bobrov/ionic-img-cache#debug

**Comment by Dofarian** [comment]
Thank you so much Vitaliy for everything.

**Comment by vitaliy-bobrov** [comment]
You're welcome :)
