### ISSUE TITLE
Manual cache directive/service

### ISSUE THREAD

**Issue by ChromaticMind** [vitaliy-bobrov/ionic-img-cache#14]
Hey @vitaliy-bobrov, 

Amazing plugin, it's really awesome and works very well.

Any chance there is / can be a way to manually cache an image via a function or something? We have two image sizes and in some use-cases we have a custom script downloading the other image along with the original one but it isn't an ideal solution. Something like ```cacheSrcStorage.get('img-path')``` would be fantastic

Looking forward to your thoughts on this - Many thanks!

**Comment by vitaliy-bobrov** [comment]
It is not implemented yet, but I'll add this feature in the next release

**Comment by vitaliy-bobrov** [comment]
@AshishMehra , check new version - 1.2.0, I've added bunch of useful methods to `ionImgCacheSrv`, see https://github.com/vitaliy-bobrov/ionic-img-cache#cache-service-public-methods

Let me know if you'll face any issues.
