### ISSUE TITLE
IPAD2 app crash with memory leakage error

### ISSUE THREAD

**Issue by dodomui** [vitaliy-bobrov/ionic-img-cache#15]
While running with IPAD 2 with IOS9, to load 10 images which total size for 10 images is around 2MB. keep receive memory warning in xcode. then app might crash for first initial which start to cache the image.

**Comment by vitaliy-bobrov** [comment]
@dodomui, could you provide more details to investigate issue:
1. ionic-img-cache version
2. cordova version
3. cordova plugins version
4. imgcachejs version
5. cordova configuration

**Comment by vitaliy-bobrov** [comment]
@dodomui , re-open after details will be provided.

**Comment by dodomui** [comment]
Really sorry for my late reply.
After investigate those days, I found it wasn't ionic-img-cache issue.
It was the issue of Ionic V1 slide-box. Need to load image into slide-box one by one else will cause memory leakage in ipad especially.

Question close and again sorry for wrong case raised.

**Comment by vitaliy-bobrov** [comment]
@dodomui, thanks for the reply, nice to hear that your problem was solved 😊
