### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by imrealashu** [vitaliy-bobrov/ionic-img-cache#22]
Uncaught TypeError: angular.module(...).run(...).provider(...).factory(...).directive(...).directive(...).component is not a function
    at ionic-img-cache.js:10
    at ionic-img-cache.js:327

Angular version 1.4.3
Please look into this issue.

**Comment by vitaliy-bobrov** [comment]
For angular < 1.5 use ionic-img-cache v1.2

**Comment by vitaliy-bobrov** [comment]
@imrealashu , try v1.3.1 it add component declaration optionally, should work for you.
