### ISSUE TITLE
AngularJS Minification friendly

### ISSUE THREAD

**Issue by aitoraznar** [vitaliy-bobrov/ionic-img-cache#24]
To be able to minify the code without problems some changes must be made and to avoid this error:
https://docs.angularjs.org/error/$injector/strictdi?p0=init

*ionic-img-cache.js*
`
angular.module('ionicImgCache', ['ionic'])
    .run(['$ionicPlatform', 'ionicImgCache', '$log', init])
    .provider('ionicImgCache', ionicImgCacheProvider)
    .factory('ionImgCacheSrv', ['$q', ionImgCacheSrv])
    .directive('ionImgCache', ['ionImgCacheSrv', ionImgCache])
    .directive('ionImgCacheBg', ['ionImgCacheSrv', ionImgCacheBg]);
`

**Comment by vitaliy-bobrov** [comment]
@aitoraznar, module already includes minified version, check out `ionic-img-cache.min.js` file. On build step before new version publication `ng-annotate` used to inject all dependencies.

**Comment by aitoraznar** [comment]
You can close it if you want.
