### ISSUE TITLE
ionImgCacheSrv.get doesn't work as expected

### ISSUE THREAD

**Issue by aitoraznar** [vitaliy-bobrov/ionic-img-cache#27]
Why doesn't return the cached file? it is lost in **file_entry !== null** instead of passing it back.

`
// checks if a copy of the file has already been cached // Reminder: this is an asynchronous method! 
// Answer to the question comes in response_callback as the second argument (first being the path) 
    ImgCache.isCached = function (img_src, response_callback) { 
        ImgCache.getCachedFile(img_src, function (src, file_entry) { 
          response_callback(src, file_entry !== null); 
       }); 
    };
`

And then
`
ImgCache.isCached(src, function(path, cached) {
    defer.resolve(cached);
}, defer.reject);
`

I'm also using this to cache other types of files manually (PDF)

Thanks for your effort

**Comment by vitaliy-bobrov** [comment]
@aitoraznar, what code example have you provided?

`ionImgCacheSrv.get` uses `ImgCache.isCached` and it returns file path if file already cached, this behavior is documented in README.

What do mean under "doesn't work as expected"?

**Comment by aitoraznar** [comment]
My version (1.3.1) returns a boolean called "success" that is calculated here **file_entry !== null**

I expect that **ionImgCacheSrv.get** gets the cached file, instead of that I receive the same path I have passed previously (http://....).

I have modified myself the library to return the cached file

**Comment by aitoraznar** [comment]
You can close it if you want.
