### ISSUE TITLE
ios not persisting images

### ISSUE THREAD

**Issue by aotaduy** [vitaliy-bobrov/ionic-img-cache#3]
Hello, 

I've implemented the cache in a ionic application, and is working fine in android. But is not persisting the images in the cache after the app reloads.  So is loading all images again every time the app starts, once in the application is working fine and images get cached.

Thanks for this great directive!

**Comment by aotaduy** [comment]
Sorry tested better and is working

**Comment by vitaliy-bobrov** [comment]
Hi, thanks for your report, please inform me if something will not work.
