### ISSUE TITLE
iOS 11 not showing cached images

### ISSUE THREAD

**Issue by fernandoamorim** [vitaliy-bobrov/ionic-img-cache#31]
![36337758-232e20f2-1385-11e8-97ea-48b098386025](https://user-images.githubusercontent.com/10285234/38038834-4ed9a368-3282-11e8-8a06-fafd538c58e0.png)
)

In Android working fine, but in iOS not show cached images. Why?!?

**Comment by suisun2015** [comment]
I'm feeling the same sometimes, anyhow I wonder if it is due to WKWebView.
After migrating from UIWebView, I frequently meet such unpleasant image missings.

**Comment by fernandoamorim** [comment]
Thanks  @suisun2015 !!!
