### ISSUE TITLE
Problem with iOS 10

### ISSUE THREAD

**Issue by ol3j** [vitaliy-bobrov/ionic-img-cache#4]
I used the plugin for app in ionic 1. 
I have the error on iOS 10 iPhone 5s & iPhone 6s  but it works on iPhone with iOs 9.x.

> TypeError: undefined is not an object (evaluating 'ImgCache.$deferred.resolve')
> callbackFromNative — cordova.js:314
> nc2 — cordova.js:1022

I see that images are saved

-[CDVFileTransferDelegate connection:didReceiveResponse:] [Line 760] Streaming to file /var/mobile/Containers/Data/Application/32E768D3-DEA2-448C-A954-C631FDC72F6C/Library/files/imgcache/1f78cf0b1e56a9fdc197149a6fd013a0ca8d4e14.logo

 -[CDVFileTransferDelegate connectionDidFinishLoading:] [Line 626] File Transfer Download success
2016-10-16 19:00:21.737798 
[1036:282954] File Transfer Finished with response code 201

Best 
ol3j

**Comment by vitaliy-bobrov** [comment]
@ol3j , unfortunately I haven't device with iOS 10 now for testing, but I'll create separate branch for workarounds and will ask you to test it. Thank you for find this issue.

**Comment by ol3j** [comment]
@vitaliy-bobrov ok, create a branch and I will test it.

**Comment by vitaliy-bobrov** [comment]
@ol3j, try to use latest version 1.1.1 - I've fixed some bugs here.
Tell me if problem appears again.

**Comment by vitaliy-bobrov** [comment]
Closing in case no response.
