### ISSUE TITLE
Image cache is not working in Android Web View >= 54 

### ISSUE THREAD

**Issue by samihu** [vitaliy-bobrov/ionic-img-cache#5]
We are using image cache in our ionic application from last 4-5 months and it was working fine till now with meta tag:

<meta http-equiv="Content-Security-Policy" content="default-src 'self'  gap://ready file://* *; style-src 'self' 'unsafe-inline'; script-src  'self' 'unsafe-inline' 'unsafe-eval';">

Image cache is not working in android web view >=54. (cdvfile images which are persisted in localstorage is not loading).
 Can you check this once?

**NOTE:**  image cache is working fine with following meta tag:

<meta http-equiv="Content-Security-Policy" content="default-src 'self'  gap://ready file://* cdvfile://* *; style-src 'self' 'unsafe-inline'; script-src  'self' 'unsafe-inline' 'unsafe-eval';">

**Comment by vitaliy-bobrov** [comment]
Could you specify the meta tag?

**Comment by vitaliy-bobrov** [comment]
try to add preference for android platform in your config.xml file
`<preference name="AndroidPersistentFileLocation" value="Compatibility" />`
in case that by default param for cordova file plugin changed, [see](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-file/index.html#android-quirks).
