### ISSUE TITLE
Unknown provider: $ionicImgCacheProvider

### ISSUE THREAD

**Issue by almothafar** [vitaliy-bobrov/ionic-img-cache#7]
When I try to configure the `$ionicImgCacheProvider` I get the unknown provider error message, but instead it must be `ionicImgCacheProvider` without `$` sign.

It is README fix only.

It's defined like this inside ionic-img-cache.js:

`.provider('ionicImgCache', ionicImgCacheProvider)`

**Comment by vitaliy-bobrov** [comment]
Yes it was mistake in readme, I've fixed it. Thank you! :)
